INSERT INTO provincias ( id, nombre ) VALUES
('1', 'Pinar del Río'),
('2', 'Artemisa'),
('3', 'Mayabeque'),
('4', 'La Habana'),
('5', 'Matanzas'),
('6', 'Villa Clara'),
('7', 'Cienfuegos' ),
('8', 'Sancti Spiritu'),
('9', 'Ciego de Ávila'),
('10', 'Camagüey'),
('11', 'Las Tunas'),
('12', 'Holguín'),
('13', 'Granma'),
('14', 'Santiago de Cuba'),
('15', 'Guantánamo'),
('16', 'Isla de la Juventud'),
('17', 'Baracoa');
